// Code generated by `make stamp`. DO NOT EDIT.

package arti

// rustFingerprint identifies the Rust sources the linked
// libarti_ffi.a was built from.
//
// It exists only to be part of this package's source. Go does not hash
// the static library named in #cgo LDFLAGS, so without a Go-visible
// change a rebuilt library is silently ignored in favour of a cached
// binary. Keeping this in step with the Rust is what makes
// `make lib && go build` produce a binary containing the new library.
const rustFingerprint = "a34ce697585e2854"
